/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SelectionImport } from './routes/selection'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const SelectionRoute = SelectionImport.update({
  id: '/selection',
  path: '/selection',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/selection': {
      id: '/selection'
      path: '/selection'
      fullPath: '/selection'
      preLoaderRoute: typeof SelectionImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/selection': typeof SelectionRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/selection': typeof SelectionRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/selection': typeof SelectionRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/selection'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/selection'
  id: '__root__' | '/' | '/selection'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SelectionRoute: typeof SelectionRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SelectionRoute: SelectionRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/selection"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/selection": {
      "filePath": "selection.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
